version: "2"

services:
  auth-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.auth-service
    environment:
      - DATABASE_URL=postgres://smorgasbord:smorgasbord@auth-service-db/auth
    ports:
      - 8080:8080

  auth-service-db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: smorgasbord
      POSTGRES_PASSWORD: smorgasbord
      POSTGRES_DB: auth
    ports:
      - 5432:5432
    volumes:
      - auth-service-db-data:/var/lib/postgresql/data

  posts-service:
    build:
      context: .
      dockerfile: docker/Dockerfile.posts-service
    ports:
      - 3000:3000

volumes:
  auth-service-db-data:
