subgraphs:
  auth-service:
    routing_url: http://localhost:8080
    schema: 
      subgraph_url: http://localhost:8080
  posts-service:
    routing_url: http://localhost:3000/graphql
    schema: 
      subgraph_url: http://localhost:3000/graphql
