name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust_tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: smorgasbord
          POSTGRES_PASSWORD: smorgasbord
          POSTGRES_DB: auth
        ports:
          - 5432:5432

    env:
      CARGO_TERM_COLOR: always
      DATABASE_URL: postgres://smorgasbord:smorgasbord@localhost/auth

    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: cargo lint --verbose
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  node_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - run: yarn workspace posts-service test
    - run: yarn workspace posts-service test:e2e

  auto-merge:
    needs: ['rust_tests', 'node_tests']
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
